# Generated by Django 5.2 on 2025-04-27 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0002_alter_deffered_payments_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deffered_payments',
            name='date',
        ),
        migrations.AddField(
            model_name='deffered_payments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='agent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date_of_payment',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='item_bought_on_credit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='quantity',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='unit_price',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount_received',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='branch_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 27, 22, 54, 15, 958479)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='issued_to',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='unit_price',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issued_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_branch_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time_of_produce',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_cost',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
