# Generated by Django 5.2 on 2025-04-27 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0003_remove_deffered_payments_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
        migrations.AddField(
            model_name='sales',
            name='date_of_sales',
            field=models.DateField(default=datetime.datetime(2025, 4, 27, 23, 31, 54, 701939)),
        ),
    ]
