# Generated by Django 5.2 on 2025-05-02 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0005_product_alter_sales_date_of_sales_administrator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deffered_payments',
            old_name='item_bought_on_credit',
            new_name='item_bought',
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_sales',
            field=models.DateField(default=datetime.datetime(2025, 5, 2, 12, 23, 50, 390012)),
        ),
    ]
