# Generated by Django 5.2 on 2025-05-02 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0006_rename_item_bought_on_credit_deffered_payments_item_bought_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_of_sales',
            field=models.DateField(default=datetime.datetime(2025, 5, 2, 12, 27, 22, 844047)),
        ),
    ]
