# Generated by Django 5.2 on 2025-05-03 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0007_alter_sales_date_of_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='sales_agent',
        ),
        migrations.RemoveField(
            model_name='salesagent',
            name='user',
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_sales',
            field=models.DateField(default=datetime.datetime(2025, 5, 3, 10, 21, 25, 586709)),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='SalesAgent',
        ),
    ]
