# Generated by Django 5.2 on 2025-05-04 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0009_receipt_alter_sales_date_of_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_contact',
            new_name='stock_time_of_arrival',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stock_time_of_produce',
            new_name='supplier_contact',
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_sales',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 17, 34, 30, 363992)),
        ),
    ]
