# Generated by Django 5.2 on 2025-05-04 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0010_rename_stock_contact_stock_stock_time_of_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_sales',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 17, 37, 40, 804305)),
        ),
    ]
