# Generated by Django 5.2 on 2025-05-06 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0011_stock_created_at_alter_sales_date_of_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_of_sales',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 7, 35, 29, 606924)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time_of_arrival',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 7, 35, 29, 605983)),
        ),
    ]
