# Generated by Django 5.2 on 2025-05-06 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0012_alter_sales_date_of_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_of_sales',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 7, 39, 20, 412729)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time_of_arrival',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 6, 7, 39, 20, 411760), null=True),
        ),
    ]
